### ISSUE TITLE
error: failed to fetch some objects from 'https://github.com/dpgiakatos/gnn-internet-data.git/info/lfs'

### ISSUE THREAD

**Issue by usama99** [dpgiakatos/gnn-internet-data#1]
I have started tracking some files (link-prediction.txt and node-classification.txt) using git-lfs. 

However, I could not fetch it due to the following error. After searching [[reference](https://stackoverflow.com/posts/62855597/timeline)], I got to know that this error message usually means that the file wasn't uploaded. 

Can you please look into it? 

TIA

![image](https://user-images.githubusercontent.com/31574039/207537433-1241e292-54cd-47bf-a2db-c96ee1c922fc.png)

**Comment by dpgiakatos** [comment]
Hello, I have removed git LFS from this repository; this is why you get the following error. To fix it, you should either delete all the git LFS files from your local repo or clone it again using `git clone https://github.com/dpgiakatos/gnn-internet-data.git`. Please read the new instructions in the dataset folder if you do the second option.

**Comment by usama99** [comment]
Thank you for the prompt response.
I have removed the existing project and cloned it again, but unfortunately, having the same errors. Is it possible to access the results (i.e., link-prediction.txt and node-classification.txt) directly, or any other way to fetch them?

**Comment by dpgiakatos** [comment]
I have downloaded the repo using `git clone https://github.com/dpgiakatos/gnn-internet-data.git` without errors. If you have the same error, your directory still has the git lfs configured. You can get the results from the paper:

- From ACM library: https://dl.acm.org/doi/abs/10.1145/3565473.3569187
- From arxiv: https://arxiv.org/pdf/2210.14189.pdf

**Comment by dpgiakatos** [comment]
I fixed the files in the repo. So you can download again using `git clone https://github.com/dpgiakatos/gnn-internet-data.git`. Also, you can get the results from the paper:

- ACM library: https://dl.acm.org/doi/abs/10.1145/3565473.3569187
- arxiv: https://arxiv.org/pdf/2210.14189.pdf

**Comment by usama99** [comment]
Thank you. It's working now.
